### ISSUE TITLE
whether use the elasticsearch java Rest Client or the  Spring Data Elasticsearch

### ISSUE THREAD

**Issue by compasses** [jettro/elasticclientdemo#1]
Hi, very glad to found you blog about the elasticsearch java rest client. but i still bouncing about them.
So what do you think about Spring Data Elasticsearch?
thanks.

**Comment by jettro** [comment]
Depending on what you want to do with elastic it is fine. It helps you maintaining the connection, does not make you create all the basic queries and it exposes the elastic java api so you can construct your own queries when needed. Of course it does limit you in flexibility that you would have using the java client directly. If you have spring data experience, spring data elastic can be a good choice, if you don't, I'd go for the direct approach. The Java Rest Client is still very basic. You have to do a lot yourself.

**Comment by compasses** [comment]
Ok, got it, big thanks, I think the java rest client should be the best choice for me.
